runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: .65
  min_instances: 1
  max_instances: 10

handlers:
  # Serve images, icons, and json from React build
  - url: /static/css/(.*\.css)
    static_files: components/build/static/css/\1
    upload: components/build/static/css/.*\.css

  # Serve JS from React build
  - url: /static/js/(.*\.js)
    static_files: components/build/static/js/\1
    upload: components/build/static/js/.*\.js

  # Let Flask handle all other routes (serving the index.html for other routes for React SPA routing)
  - url: /.*
    script: auto

env_variables:
  SECRET_KEY: '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'

