runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: .65
  min_instances: 1
  max_instances: 10

handlers:

  # Serve images, icons, and json from React build
  - url: /(.*\.(json|ico|jpg|png|svg))
    static_files: src/components/build/\1
    upload: src/components/build/.*\.(json|ico|jpg|png|svg)$

  # Serve CSS from React build
  - url: /static/css/(.*\.css)
    static_files: src/components/build/static/css/\1
    upload: src/components/build/static/css/.*\.css$

  # Serve JS from React build (adjust if you have a JS directory similar to the CSS path you provided)
  - url: /static/js/(.*\.js)
    static_files: src/components/build/static/js/\1
    upload: src/components/build/static/js/.*\.js$

  # Let Flask handle all other routes
  - url: /.*
    script: auto

env_variables:
  OPENAI_API_KEY: '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'
